config/routes.rb
Rails.application.routes.draw do
  devise_for :doctors
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "landing_page#index"
  namespace :admin do
    resource :dashboard, only: [:show]
    resources :hospitals, only: [:show, :index, :edit, :destroy, :new, :update, :create] do
      resources :doctors
    end
    resources :appointments
  end

  namespace :doctors do
    resource :dashboard, only: [:show]
    resources :appointments
  end
end

app/models/appointment.rb
class Appointment < ApplicationRecord
  validates :date, presence: true

  belongs_to :doctor
  belongs_to :patient
  belongs_to :hospital
  before_validation :set_defaults

  scope :date_asc, -> { order(date: :asc) }

  def upcoming?
    if start_time && ((date > Date.current) || (date == Date.current && start_time.strftime("%H:%M:%S") > Time.current.strftime("%H:%M:%S")))
      true
    end
  end

  def slot_time
    "#{start_time.strftime("%I:%M %p")} - #{end_time.strftime("%I:%M %p")}" if start_time? && end_time?
  end

  def formated_start_time
    "#{start_time&.strftime("%I:%M %p")}"
  end

  def formated_end_time
    "#{end_time&.strftime("%I:%M %p")}"
  end

  private
    def set_defaults
      self.hospital ||= doctor&.hospital
    end
end

app/models/doctor.rb
class Doctor < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  REQUIRED_HOSPITAL_ROLES = ["doctor", "receptionist"]
  enum role: { doctor: 'doctor', admin: 'admin', receptionist: "receptionist" }

  validate :check_hospital

  belongs_to :hospital, optional: true

  has_many :appointments
  has_many :patients, through: :appointments

  def email_required?
    false
  end

  def password_required?
    false
  end

  private
    def check_hospital
      if !hospital_id && REQUIRED_HOSPITAL_ROLES.include?(role)
        errors.add(:hospital, "Required hospital")
      end
    end
end

app/controllers/admin/appointments_controller.rb
module Admin
  class AppointmentsController < BaseController
    def index
    end
  end
end

app/controllers/admin/doctors_controller.rb
module Admin
  class DoctorsController < BaseController
    before_action :set_hospital
    before_action :set_doctor, only: %i[show, new, edit, destroy, update]

    def index
      @doctors = @hospital.doctors
    end

    def show
    end

    private
      def set_doctor
        @doctor = @hospital.doctors.find(id: params[:id])
      end

      def set_hospital
        @hospital = Hospital.find(id: params[:hospital_id])
      end
  end
end

app/controllers/doctors/appointments_controller.rb
module Doctors
  class AppointmentsController < BaseController
    before_action :set_appointment, only: [:show, :edit, :update, :destroy]

    def show
    end

    def index
      @appointments = current_hospital.appointments.date_asc
      @appointments = @appointments.joins(:patient, :doctor).where("lower(patients.name) LIKE ? OR lower(doctors.name) LIKE ?", "%#{params[:query].downcase}%", "%#{params[:query].downcase}%") if params[:query].present?
    end

    def new
      @patient = current_hospital.patients.new
    end

    def create
      @patient = current_hospital.patients.new(patient_params)
      appointment = @patient.appointments.build(appointment_params)
      appointment.hospital = current_hospital
      if @patient.save
        redirect_to doctors_appointments_path, notice: "appointment has been successfully created."
      else
        flash[:error] = "#{@patient.errors.full_messages.to_sentence}, #{appointment.errors.full_messages.to_sentence}"
        render :new
      end
    end

    def edit
    end

    def update
      if @patient.update(patient_params) && @appointment.update(appointment_params)
        redirect_to doctors_appointments_path, notice: 'Appointment has been updated successfully.'
      else
        flash[:error] = "#{@patient.errors.full_messages.to_sentence}, #{@appointment.errors.full_messages.to_sentence}"
        render :edit
      end
    end

    def destroy
      if @appointment.destroy
        redirect_to doctors_appointments_path, notice: 'Appointment has been successfully destroyed.'
      else
        flash[:error] = @appointment.errors.full_messages.to_sentence
        redirect_to doctors_appointments_path
      end
    end

    private
      def set_appointment
        @appointment = current_hospital.appointments.find(params[:id])
        @patient = @appointment.patient
      end

      def patient_params
        params.required(:patient).permit(:name, :email, :phone, :image).compact_blank
      end

      def appointment_params
        params.permit(:doctor_id, :date, :start_time, :end_time).compact_blank
      end
  end
end

app/controllers/doctors/base_controller.rb
module Doctors
  class BaseController < ApplicationController
    before_action :authenticate_doctor!
    before_action :current_hospital

    helper_method :current_hospital

    def current_hospital
      @current_hospital ||= current_doctor&.hospital
    end
  end
end

app/controllers/doctors/dashboards_controller.rb
module Doctors
  class DashboardsController < BaseController
    def show
      @all_appointments = begin
        patients = current_hospital.patients.group("date(patients.created_at)").count.sort.to_h
        {
          dates: patients.keys,
          series: [
            {name: "Patients", data: patients.values}
          ]
        }
      end
    end
  end
end

app/views/doctors/appointments/_form.html.erb
<%= simple_form_for(@patient, local: true, html: { multipart: true }, url: (@patient.persisted? ? doctors_appointment_path(@appointment) : doctors_appointments_path)) do |form| %>

  <div class="form-group">
    <%= form.label :name, class: "form-label" %>
    <%= form.text_field :name, autofocus: true, class: "form-control", placeholder: "Name" %>
  </div>

  <div class="form-group">
    <%= form.label :phone, class: "form-label" %>
    <%= form.text_area :phone, class: "form-control", placeholder: "Phone" %>
  </div>

  <div class="form-group">
    <%= form.label :doctor %>
    <%= select_tag(:doctor_id, options_from_collection_for_select(current_hospital.doctors.doctor, :id, :name, selected: @appointment&.doctor_id), class: "form-control", prompt: "Select Doctor") %>
  </div>

  <div class="form-group">
    <%= form.label :email, class: "form-label" %>
    <%= form.text_area :email, class: "form-control", placeholder: "email" %>
  </div>

  <div class="form-group">
    <%= form.label :date %>
    <%= date_field_tag "date", nil, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :start_time %>
    <%= select_tag(:start_time, options_for_select(TIME_SLOTS, selected: @appointment&.start_time), class: "form-control", prompt: @appointment&.formated_start_time || "Select start time") %>
  </div>

  <div class="form-group">
    <%= form.label :end_time %>
    <%= select_tag(:end_time, options_for_select(TIME_SLOTS), class: "form-control", prompt: @appointment&.formated_end_time || "Select end time") %>
  </div>

  <div class="image d-flex flex-column">
    <%= form.input_field :image, class: "image-upload my-2" %>
    <%= image_tag("#{form.object.image.url if form.object.image.attached?}", alt: "", class: "preview-image", width: "80px", height: "80px", style: form.object.image.attached? ? "" : "display: none;") %>
  </div>

  <div class="form-group">
    <%= form.submit "Submit", class: "btn btn-primary btn-block" %>
  </div>
<% end %>

app/views/doctors/appointments/edit.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-6">
      <h2 class="text-center my-4">Edit Appointment </h2>
        <%= render 'form' %>
    </div>
  </div>
</div>

app/views/doctors/appointments/index.html.erb
<div class="py-5">
  <div class="d-flex justify-content-end"><%= link_to 'New Appointment', new_doctors_appointment_path, class: "btn btn-primary button-color" %></div>
    <div class="card-toolbar mt-sm-0 mt-2">
      <div class="d-flex align-items-center">
        <div class="mx-1"><%= render "shared/search_form" %></div>
      </div>
    </div>
  <table class="table table-bordered mt-4">
    <thead class="table-dark">
      <tr>
        <th>#</th>
        <th>Patient Name</th>
        <th>Doctor Name</th>
        <th>Date</th>
        <th>Status</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
      <% if @appointments.present? %>
        <% @appointments.each do |appointment| %>
          <tr>
            <td><%= appointment.id %></td>
            <td><%= appointment.patient.name %></td>
            <td><%= appointment.doctor.name %></td>
            <td><%= appointment.date&.to_date %></td>
            <td><%= appointment_status(appointment) %></td>
            <td >
              <%= link_to 'Show', doctors_appointment_path(appointment), class: "btn btn-success" %>
              <%= link_to 'Edit', edit_doctors_appointment_path(appointment), class: "btn btn-warning #{disabled_edit_delete}" %>
              <%= link_to 'Delete', doctors_appointment_path(appointment), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger #{disabled_edit_delete}" %>
            </td>
          </tr>
        <% end %>
      <% else %>
        <tr>
          <td colspan="9" class="text-center">No patients found.</td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/doctors/appointments/new.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-6">
      <h2 class="text-center my-4">Create Appointment </h2>
        <%= render 'form' %>
    </div>
  </div>
</div>

app/views/doctors/appointments/show.html.erb
<section class="w-100 px-4 py-5" style="border-radius: .5rem .5rem 0 0;">
  <div class="row d-flex justify-content-center">
    <div class="col col-md-9 col-lg-7 col-xl-6">
      <div class="card" style="border-radius: 15px;">
        <div class="card-body p-4">
          <div class="d-flex">
            <div class="flex-shrink-0">
              <img src="<%= profile_image(@appointment.patient) %>"
                alt="Generic placeholder image" class="img-fluid" style="width: 180px; border-radius: 10px;">
            </div>
            <div class="flex-grow-1 ms-3">
              <h5 class="mb-1"><%= @appointment.patient.name.presence || "No Name" %></h5>
              <div class="d-flex justify-content-start rounded-3 p-2 mb-2 bg-body-tertiary">
                <div>
                  <p class="small text-muted mb-1">Email: <%= @appointment.patient.email %></p>
                  <p class="small text-muted mb-1">Phone: <%= @appointment.patient.phone %></p>
                  <p class="small text-muted mb-1">Doctor Name: <%= @appointment.doctor.name %></p>
                  <p class="small text-muted mb-1">Date: <%= @appointment.date&.to_date %></p>
                  <p class="small text-muted mb-1">Slot: <%= "#{@appointment.slot_time}" %></p>
                </div>
              </div>
              <div class="d-flex pt-1">
               <%# <button  type="button" data-mdb-button-init data-mdb-ripple-init class="btn btn-outline-primary me-1 flex-grow-1">Chat</button> %>
               <%= appointment_status(@appointment) %>
                <%# <button  type="button" data-mdb-button-init data-mdb-ripple-init class="btn btn-primary flex-grow-1">Follow</button> %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>