config/routes.rb
Rails.application.routes.draw do
  devise_for :doctors
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "landing_page#index"
  namespace :admin do
    resource :dashboard, only: [:show]
    resources :hospitals, only: [:show, :index, :edit, :destroy, :new, :update, :create] do
      resources :doctors
    end
    resources :appointments
  end

  namespace :doctors do
    resource :dashboard, only: [:show]
    resources :appointments
  end
end

app/views/shared/_admin_header.html.erb
<header class="header-background-color text-white">
  <nav class="navbar navbar-expand-lg navbar-dark">
    <a class="navbar-brand" href="#"><%= respond_to?(:current_hospital) ? current_hospital.name.presence || "eHospital" : "eHospital" %></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
      <% if doctor_signed_in? %>
        <ul class="navbar-nav ml-auto text-white ">
          <li class="nav-item">
            <a class="nav-link text-white" href="<%= admin_hospitals_path %>">Hospitals</a>
          </li>
          <li class="nav-item">
            <a class="nav-link text-white" href="#">Contact</a>
          </li>
          <li class="nav-item">
            <%= link_to "Log out", destroy_doctor_session_path, method: :delete, class: "btn btn-light text-primary", form_class: "d-inline" %>
          </li>
        </ul>
      <% end %>
    </div>
  </nav>
</header>

app/views/shared/_errors_message.html.erb
<% flash.each do |type, msg| %>
  <% type = "error" if type == "alert" %>
  <div class="alert alert-<%= type %> alert-dismissible m-2 fade show flash-message" role="alert">
    <%= msg %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>
<style>
  .flash-message {
    animation: fadeOut 15s forwards;
  }
  @keyframes fadeOut {
    0% {
      opacity: 1;
      transform: translateY(0);
    }
    100% {
      opacity: 0;
      transform: translateY(-100%);
      display: none;
    }
  }
</style>

app/views/shared/_footer.html.erb
<section class="hero bg-light text-center py-5 vh-100">
  <div class="container">
    <h1 class="display-4">Welcome to eHospital</h1>
    <p class="lead">Your one-stop shop for all your needs</p>
    <a href="#" class="btn btn-primary btn-lg">Welcome</a>
  </div>
</section>

app/views/shared/_header.html.erb
<header class="header-background-color text-white">
  <nav class="navbar navbar-expand-lg navbar-dark">
    <a class="navbar-brand" href="#">eHospital</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item">
          <a class="nav-link" href="/">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Contact</a>
        </li>
        <li class="nav-item">
          <a class="btn btn-light text-primary" href="<%= new_doctor_session_path %>">Login</a>
        </li>
      </ul>
    </div>
  </nav>
</header>

app/views/shared/_search_form.html.erb
<%= form_tag request.url, method: :get, class: "row g-3", id: '' do %>
  <span class="d-flex">
    <%= text_field_tag(:query, params[:query], { placeholder: "Search....", class: "form-control text-center" }) %>
    <%= submit_tag("Submit") %>
  </span>
<% end %>

app/views/shared/_user_header.html.erb
<header class="header-background-color text-white">
  <nav class="navbar navbar-expand-lg navbar-dark">
    <a class="navbar-brand" href="#"><%= respond_to?(:current_hospital) ? current_hospital.name.presence || "eHospital" : "eHospital" %></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
      <% if doctor_signed_in? %>
        <ul class="navbar-nav ml-auto text-white ">
          <li class="nav-item">
            <% appointments_path = current_doctor.admin? ? admin_appointments_path : doctors_appointments_path %>
            <a class="nav-link text-white" href="<%= appointments_path %>">Appointments</a>
          </li>
          <% if current_doctor.admin? %>
            <li class="nav-item">
              <a class="nav-link text-white" href="<%= admin_hospitals_path %>">Hospitals</a>
            </li>
          <% end %>
          <li class="nav-item">
            <a class="nav-link text-white" href="#">Contact</a>
          </li>
          <li class="nav-item">
            <%= link_to "Log out", destroy_doctor_session_path, method: :delete, class: "btn btn-light text-primary", form_class: "d-inline" %>
          </li>
        </ul>
      <% end %>
    </div>
  </nav>
</header>